---
- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Check if k3s service is running
  systemd:
    name: k3s
  register: k3s_service
  ignore_errors: yes

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - \
      --write-kubeconfig-mode=644 \
      --node-name=pilot-hdc-lite \
      --cluster-init
  become: yes
  when: not k3s_binary.stat.exists or k3s_service.status.ActiveState != "active"

- name: Wait for k3s to be ready
  wait_for:
    port: 6443
    host: localhost
    timeout: 120

- name: Wait for node to be ready
  shell: kubectl get nodes --no-headers | grep -q Ready
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: node_ready
  until: node_ready.rc == 0
  retries: 24
  delay: 10
  become: yes
