---
- name: Create .kube directory for ubuntu user
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  become: yes

- name: Copy k3s kubeconfig for ubuntu user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ubuntu/.kube/config
    mode: '0600'
    owner: ubuntu
    group: ubuntu
    remote_src: yes
  become: yes

- name: Wait until kubectl can talk to the API server
  command: kubectl get nodes --no-headers
  register: kubectl_test
  retries: 15          # ~2.5 min total
  delay: 10
  until: kubectl_test.rc == 0
  changed_when: false
  become: false

- name: Display kubectl test result
  debug:
    var: kubectl_test.stdout_lines
